### ISSUE TITLE
로그인 무작정 성공 문제

### ISSUE THREAD

**Issue by HyunseungYu** [UnivCert/univcert-web#16]
API 사용하고 싶어서 회원가입을 하는데
로그인에 아무 값이나 넣어도 로그인 성공!이 떠요
백엔드는 괜찮은 것 같은데 프론트에서 문제가 있나 싶어요

**Comment by andy000923** [comment]
아마도 프론트에서 연결된 api에 문제가 있었던 것 같아요. 지금은 해결 되었습니다~^^
